export const data = {
  categories: [
    {
      id: "general",
      name: "General Knowledge",
      questions: [
        {
          id: 1,
          question: "What is the capital of France?",
          options: ["Paris", "London", "Rome", "Berlin"],
          answer: "Paris",
          img: "https://cdn.pixabay.com/photo/2015/03/26/09/54/eiffel-tower-690293_1280.jpg",
        },
        {
          id: 2,
          question: "Who wrote '1984'?",
          options: [
            "George Orwell",
            "Mark Twain",
            "J.K. Rowling",
            "Ernest Hemingway",
          ],
          answer: "George Orwell",
          img: "https://cdn.pixabay.com/photo/2017/03/16/11/40/george-orwell-2149860_1280.jpg",
        },
        {
          id: 3,
          question: "Which planet is known as the Red Planet?",
          options: ["Mars", "Venus", "Jupiter", "Saturn"],
          answer: "Mars",
          img: "https://cdn.pixabay.com/photo/2014/12/21/23/39/mars-575545_1280.jpg",
        },
        {
          id: 4,
          question: "How many continents are there on Earth?",
          options: ["5", "6", "7", "8"],
          answer: "7",
          img: "https://cdn.pixabay.com/photo/2013/07/12/15/12/world-map-150935_1280.png",
        },
        {
          id: 5,
          question: "What is the largest ocean?",
          options: ["Atlantic", "Indian", "Pacific", "Arctic"],
          answer: "Pacific",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/ocean-1867277_1280.jpg",
        },
        {
          id: 6,
          question: "Who painted the Mona Lisa?",
          options: [
            "Leonardo da Vinci",
            "Vincent van Gogh",
            "Pablo Picasso",
            "Michelangelo",
          ],
          answer: "Leonardo da Vinci",
          img: "https://cdn.pixabay.com/photo/2017/11/04/12/34/mona-lisa-2910193_1280.jpg",
        },
        {
          id: 7,
          question: "Which country is known as the Land of the Rising Sun?",
          options: ["China", "Japan", "Thailand", "South Korea"],
          answer: "Japan",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/japan-1867270_1280.jpg",
        },
        {
          id: 8,
          question: "What is the chemical symbol for water?",
          options: ["H2O", "O2", "CO2", "HO"],
          answer: "H2O",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/ocean-1867277_1280.jpg",
        },
        {
          id: 9,
          question: "Which is the tallest mountain in the world?",
          options: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"],
          answer: "Mount Everest",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/mountain-1867277_1280.jpg",
        },
        {
          id: 10,
          question: "Which planet is closest to the Sun?",
          options: ["Mercury", "Venus", "Earth", "Mars"],
          answer: "Mercury",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/planet-1867277_1280.jpg",
        },
      ],
    },
    {
      id: "science",
      name: "Science & Technology",
      questions: [
        {
          id: 1,
          question: "What gas do plants absorb from the atmosphere?",
          options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
          answer: "Carbon Dioxide",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/plant-1867277_1280.jpg",
        },
        {
          id: 2,
          question: "What is the chemical symbol for gold?",
          options: ["Au", "Ag", "Gd", "Go"],
          answer: "Au",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/gold-1867277_1280.jpg",
        },
        {
          id: 3,
          question: "Who developed the theory of relativity?",
          options: [
            "Isaac Newton",
            "Albert Einstein",
            "Nikola Tesla",
            "Galileo Galilei",
          ],
          answer: "Albert Einstein",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/einstein-1867277_1280.jpg",
        },
        {
          id: 4,
          question: "What part of the body controls balance?",
          options: ["Eyes", "Heart", "Inner Ear", "Lungs"],
          answer: "Inner Ear",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/ear-1867277_1280.jpg",
        },
        {
          id: 5,
          question: "What is H2O commonly known as?",
          options: ["Hydrogen", "Oxygen", "Water", "Salt"],
          answer: "Water",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/water-1867277_1280.jpg",
        },
        {
          id: 6,
          question: "What is the speed of light?",
          options: ["3x10^8 m/s", "1x10^6 m/s", "3x10^5 km/s", "3x10^7 m/s"],
          answer: "3x10^8 m/s",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/light-1867277_1280.jpg",
        },
        {
          id: 7,
          question: "Which element has the atomic number 1?",
          options: ["Hydrogen", "Helium", "Oxygen", "Carbon"],
          answer: "Hydrogen",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/hydrogen-1867277_1280.jpg",
        },
        {
          id: 8,
          question: "What is the boiling point of water at sea level?",
          options: ["90°C", "100°C", "80°C", "120°C"],
          answer: "100°C",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/boiling-1867277_1280.jpg",
        },
        {
          id: 9,
          question: "What is the study of earthquakes called?",
          options: ["Volcanology", "Seismology", "Geology", "Meteorology"],
          answer: "Seismology",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/earthquake-1867277_1280.jpg",
        },
        {
          id: 10,
          question: "Which planet has the most moons?",
          options: ["Jupiter", "Saturn", "Mars", "Earth"],
          answer: "Saturn",
          img: "https://cdn.pixabay.com/photo/2016/11/29/04/05/saturn-1867277_1280.jpg",
        },
      ],
    },
    {
      id: "webdev",
      name: "Web Development",
      questions: [
        {
          id: 1,
          question: "Which language is used for styling web pages?",
          options: ["HTML", "CSS", "JavaScript", "Python"],
          answer: "CSS",
          img: "https://cdn.pixabay.com/photo/2017/08/10/07/36/code-2616513_1280.jpg",
        },
        {
          id: 2,
          question: "What does HTML stand for?",
          options: [
            "Hyper Text Markup Language",
            "Home Tool Markup Language",
            "Hyperlinks and Text Markup Language",
            "High Text Markup Language",
          ],
          answer: "Hyper Text Markup Language",
          img: "https://cdn.pixabay.com/photo/2014/04/03/10/32/html-311610_1280.png",
        },
        {
          id: 3,
          question: "Which company developed JavaScript?",
          options: ["Microsoft", "Netscape", "Google", "IBM"],
          answer: "Netscape",
          img: "https://cdn.pixabay.com/photo/2017/01/10/19/05/javascript-1960276_1280.png",
        },
        {
          id: 4,
          question: "What does CSS stand for?",
          options: [
            "Cascading Style Sheets",
            "Creative Style Sheets",
            "Computer Style Sheets",
            "Colorful Style Sheets",
          ],
          answer: "Cascading Style Sheets",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/css-1867270_1280.jpg",
        },
        {
          id: 5,
          question: "Which HTML tag is used for line breaks?",
          options: ["<break>", "<lb>", "<br>", "<line>"],
          answer: "<br>",
          img: "https://cdn.pixabay.com/photo/2017/01/05/10/15/html-1956211_1280.png",
        },
        {
          id: 6,
          question: "Which attribute is used to link CSS files?",
          options: ["href", "src", "link", "rel"],
          answer: "href",
          img: "https://cdn.pixabay.com/photo/2017/08/10/07/36/code-2616514_1280.jpg",
        },
        {
          id: 7,
          question:
            "What is the correct syntax to write a JavaScript function?",
          options: [
            "function myFunc(){}",
            "func myFunc(){}",
            "def myFunc(){}",
            "function:myFunc(){}",
          ],
          answer: "function myFunc(){}",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/javascript-1867270_1280.jpg",
        },
        {
          id: 8,
          question: "Which symbol is used for comments in CSS?",
          options: ["//", "/* */", "#"],
          answer: "/* */",
          img: "https://cdn.pixabay.com/photo/2017/01/05/10/15/css-1956210_1280.png",
        },
        {
          id: 9,
          question: "How do you make text bold in HTML?",
          options: ["<bold>", "<b>", "<strong>", "Both <b> and <strong>"],
          answer: "Both <b> and <strong>",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/html-1867270_1280.jpg",
        },
        {
          id: 10,
          question: "Which HTML attribute specifies an image source?",
          options: ["href", "src", "link", "alt"],
          answer: "src",
          img: "https://cdn.pixabay.com/photo/2017/08/10/07/36/image-2616515_1280.jpg",
        },
      ],
    },
    {
      id: "history",
      name: "History",
      questions: [
        {
          id: 1,
          question: "Who was the first President of the United States?",
          options: [
            "George Washington",
            "Thomas Jefferson",
            "Abraham Lincoln",
            "John Adams",
          ],
          answer: "George Washington",
          img: "https://cdn.pixabay.com/photo/2017/03/16/11/40/george-washington-2149860_1280.jpg",
        },
        {
          id: 2,
          question: "In which year did World War II end?",
          options: ["1944", "1945", "1946", "1947"],
          answer: "1945",
          img: "https://cdn.pixabay.com/photo/2014/09/27/16/00/world-war-2-461000_1280.jpg",
        },
        {
          id: 3,
          question: "Who discovered America?",
          options: [
            "Christopher Columbus",
            "Leif Erikson",
            "Amerigo Vespucci",
            "Ferdinand Magellan",
          ],
          answer: "Christopher Columbus",
          img: "https://cdn.pixabay.com/photo/2016/03/31/19/03/christopher-columbus-1294621_1280.jpg",
        },
        {
          id: 4,
          question: "Which empire built the Colosseum?",
          options: ["Greek", "Roman", "Ottoman", "Egyptian"],
          answer: "Roman",
          img: "https://cdn.pixabay.com/photo/2017/03/30/12/31/colosseum-2181392_1280.jpg",
        },
        {
          id: 5,
          question: "Who was known as the Maid of Orleans?",
          options: [
            "Joan of Arc",
            "Queen Elizabeth I",
            "Catherine the Great",
            "Cleopatra",
          ],
          answer: "Joan of Arc",
          img: "https://cdn.pixabay.com/photo/2018/04/04/16/57/joan-of-arc-3294881_1280.jpg",
        },
        {
          id: 6,
          question: "What year did the Berlin Wall fall?",
          options: ["1987", "1989", "1991", "1990"],
          answer: "1989",
          img: "https://cdn.pixabay.com/photo/2014/11/15/16/55/berlin-wall-529987_1280.jpg",
        },
        {
          id: 7,
          question: "Who was the first emperor of China?",
          options: ["Qin Shi Huang", "Kublai Khan", "Sun Tzu", "Confucius"],
          answer: "Qin Shi Huang",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/terracotta-army-1867270_1280.jpg",
        },
        {
          id: 8,
          question:
            "Which war was fought between the North and South regions of the United States?",
          options: [
            "Revolutionary War",
            "Civil War",
            "World War I",
            "War of 1812",
          ],
          answer: "Civil War",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/civil-war-1867270_1280.jpg",
        },
        {
          id: 9,
          question: "Who was the famous female pharaoh of ancient Egypt?",
          options: ["Hatshepsut", "Nefertiti", "Cleopatra", "Isis"],
          answer: "Hatshepsut",
          img: "https://cdn.pixabay.com/photo/2017/02/27/16/57/hatshepsut-2103694_1280.jpg",
        },
        {
          id: 10,
          question: "Which country was Napoleon Bonaparte from?",
          options: ["France", "Italy", "Spain", "Germany"],
          answer: "France",
          img: "https://cdn.pixabay.com/photo/2017/01/10/19/05/napoleon-1960276_1280.png",
        },
      ],
    },
    {
      id: "sports",
      name: "Sports",
      questions: [
        {
          id: 1,
          question: "Which sport uses a shuttlecock?",
          options: ["Badminton", "Tennis", "Squash", "Table Tennis"],
          answer: "Badminton",
          img: "https://cdn.pixabay.com/photo/2017/07/24/09/26/badminton-2530596_1280.jpg",
        },
        {
          id: 2,
          question: "How many players are on a soccer team on the field?",
          options: ["9", "10", "11", "12"],
          answer: "11",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/soccer-1867270_1280.jpg",
        },
        {
          id: 3,
          question: "Which country won the FIFA World Cup in 2018?",
          options: ["Germany", "Brazil", "France", "Argentina"],
          answer: "France",
          img: "https://cdn.pixabay.com/photo/2018/07/16/18/05/world-cup-3530417_1280.jpg",
        },
        {
          id: 4,
          question: "In which sport is the term 'home run' used?",
          options: ["Cricket", "Baseball", "Hockey", "Tennis"],
          answer: "Baseball",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/baseball-1867270_1280.jpg",
        },
        {
          id: 5,
          question: "Which sport is known as the 'king of sports'?",
          options: ["Soccer", "Basketball", "Cricket", "Tennis"],
          answer: "Soccer",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/soccer-1867271_1280.jpg",
        },
        {
          id: 6,
          question: "How many rings are there in the Olympic symbol?",
          options: ["4", "5", "6", "7"],
          answer: "5",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/olympic-1867270_1280.jpg",
        },
        {
          id: 7,
          question: "Which tennis player has won the most Grand Slam titles?",
          options: [
            "Roger Federer",
            "Rafael Nadal",
            "Novak Djokovic",
            "Serena Williams",
          ],
          answer: "Novak Djokovic",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/tennis-1867270_1280.jpg",
        },
        {
          id: 8,
          question:
            "In which country were the first modern Olympic Games held?",
          options: ["France", "Greece", "Italy", "USA"],
          answer: "Greece",
          img: "https://cdn.pixabay.com/photo/2016/11/29/03/53/athens-1867270_1280.jpg",
        },
        {
          id: 9,
          question: "Which sport uses a puck?",
          options: ["Hockey", "Soccer", "Basketball", "Baseball"],
          answer: "Hockey",
          img: "https://cdn.pixabay.com/photo/2017/01/10/19/05/hockey-1960276_1280.jpg",
        },
        {
          id: 10,
          question: "Which country hosts the Tour de France cycling race?",
          options: ["Italy", "France", "Spain", "Belgium"],
          answer: "France",
          img: "https://cdn.pixabay.com/photo/2017/01/10/19/05/cycling-1960276_1280.jpg",
        },
      ],
    },
  ],
};
